package susen36.epicdragonfight.gameasset;

import com.mojang.math.Vector3f;
import com.mojang.math.Vector4f;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import susen36.epicdragonfight.api.client.model.Mesh;
import susen36.epicdragonfight.api.utils.math.OpenMatrix4f;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.Base64;

@OnlyIn(Dist.CLIENT)
public class DragonMeshData {
    private static final int VERTEX_COUNT = 1560;
    private static final OpenMatrix4f CORRECTION = OpenMatrix4f.createRotatorDeg(-90.0F, Vector3f.XP);

    private static final String POSITIONS_B64 =
        "AADAPkrtz0BWRiBAAADAPkrtz0BWRgxAAADAPkrt70BWRiBAAADAPkrt70BWRgxAAADAvkrt70BW"
        + "RiBAAADAvkrt70BWRgxAAADAvkrtz0BWRiBAAADAvkrtz0BWRgxAAAAAP0rts0BWRjxAAAAAP0rt"
        + "s0CsjPg/AAAAP0rt00BWRjxAAAAAP0rt00CsjPg/AAAAv0rt00BWRjxAAAAAv0rt00CsjPg/AAAA"
        + "v0rts0BWRjxAAAAAv0rts0CsjPg/AACgPkrtu0BWRkxAAACgPkrtu0BWRjxAAACgPkrtx0BWRkxA"
        + "AACgPkrtx0BWRjxAAABAPkrtx0BWRkxAAABAPkrtx0BWRjxAAABAPkrtu0BWRkxAAABAPkrtu0BW"
        + "RjxAAACgPkrt40BWRihAAACgPkrt40BWRiBAAACgPkrt60BWRihAAACgPkrt60BWRiBAAABAPkrt"
        + "60BWRihAAABAPkrt60BWRiBAAABAPkrt40BWRihAAABAPkrt40BWRiBAAABAvkrtu0BWRkxAAABA"
        + "vkrtu0BWRjxAAABAvkrtx0BWRkxAAABAvkrtx0BWRjxAAACgvkrtx0BWRkxAAACgvkrtx0BWRjxA"
        + "AACgvkrtu0BWRkxAAACgvkrtu0BWRjxAAABAvkrt40BWRihAAABAvkrt40BWRiBAAABAvkrt60BW"
        + "RihAAABAvkrt60BWRiBAAACgvkrt60BWRihAAACgvkrt60BWRiBAAACgvkrt40BWRihAAACgvkrt"
        + "40BWRiBAAACwP1jiDMBYU/8/AACwP9UyhsB9A+k/AACwP1+zCMDVsJ8/AACwP1gbhMACYYk/AAAg"
        + "P1+zCMDVsJ8/AAAgP1gbhMACYYk/AAAgP1jiDMBYU/8/AAAgP9UyhsB9A+k/AAAgv1jiDMBYU/8/"
        + "AAAgv9UyhsB9A+k/AAAgv1+zCMDVsJ8/AAAgv1gbhMACYYk/AACwv1+zCMDVsJ8/AACwv1gbhMAC"
        + "YYk/AACwv1jiDMBYU/8/AACwv9UyhsB9A+k/AACAP0cFbr7ZeoA/AACAP6MC977ZeoA/AACAP0cF"
        + "br7IsXU7AACAP6MC977IsXU7AAAAP0cFbr7IsXU7AAAAP6MC977IsXU7AAAAP0cFbr7ZeoA/AAAA"
        + "P6MC977ZeoA/AAAAv0cFbr7ZeoA/AAAAv6MC977ZeoA/AAAAv0cFbr7IsXU7AAAAv6MC977IsXU7"
        + "AACAv0cFbr7IsXU7AACAv6MC977IsXU7AACAv0cFbr7ZeoA/AACAv6MC977ZeoA/AACgPmwlCMBW"
        + "RkxAAACgPmwlCMBWRiRAAACgPuBKwL9WRkxAAACgPuBKwL9WRiRAAACgvuBKwL9WRkxAAACgvuBK"
        + "wL9WRiRAAACgvmwlCMBWRkxAAACgvmwlCMBWRiRAAACAPXAlAMBWRlxAAACAPXAlAMBWRkxAAACA"
        + "PeBK0L9WRlxAAACAPeBK0L9WRkxAAACAPeBK0L9WRlxAAACAPeBK0L9WRkxAAACAPXAlAMBWRlxA"
        + "AACAPXAlAMBWRkxAAACgPmwlMMBWRkxAAACgPmwlMMBWRiRAAACgPmwlCMBWRkxAAACgPmwlCMBW"
        + "RiRAAACgvmwlCMBWRkxAAACgvmwlCMBWRiRAAACgvmwlMMBWRkxAAACgvmwlMMBWRiRAAACAPWwl"
        + "KMBWRlxAAACAPWwlKMBWRkxAAACAPWwlEMBWRlxAAACAPWwlEMBWRkxAAACAPWwlEMBWRlxAAACA"
        + "PWwlEMBWRkxAAACAPWwlKMBWRlxAAACAPWwlKMBWRkxAAACgPmwlWMBWRkxAAACgPmwlWMBWRiRA"
        + "AACgPmwlMMBWRkxAAACgPmwlMMBWRiRAAACgvmwlMMBWRkxAAACgvmwlMMBWRiRAAACgvmwlWMBW"
        + "RkxAAACgvmwlWMBWRiRAAACAPWwlUMBWRlxAAACAPWwlUMBWRkxAAACAPWwlOMBWRlxAAACAPWwl"
        + "OMBWRkxAAACAPWwlOMBWRlxAAACAPWwlOMBWRkxAAACAPWwlUMBWRlxAAACAPWwlUMBWRkxAAACg"
        + "PrYSgMBWRkxAAACgPrYSgMBWRiRAAACgPmwlWMBWRkxAAACgPmwlWMBWRiRAAACgvmwlWMBWRkxA"
        + "AACgvmwlWMBWRiRAAACgvrYSgMBWRkxAAACgvrYSgMBWRiRAAACAPWwleMBWRlxAAACAPWwleMBW"
        + "RkxAAACAPWwlYMBWRlxAAACAPWwlYMBWRkxAAACAPWwlYMBWRlxAAACAPWwlYMBWRkxAAACAPWwl"
        + "eMBWRlxAAACAPWwleMBWRkxAAACgPrYSlMBWRkxAAACgPrYSlMBWRiRAAACgPrYSgMBWRkxAAACg"
        + "PrYSgMBWRiRAAACgvrYSgMBWRkxAAACgvrYSgMBWRiRAAACgvrYSlMBWRkxAAACgvrYSlMBWRiRA"
        + "AACAPbYSkMBWRlxAAACAPbYSkMBWRkxAAACAPbYShMBWRlxAAACAPbYShMBWRkxAAACAPbYShMBW"
        + "RlxAAACAPbYShMBWRkxAAACAPbYSkMBWRlxAAACAPbYSkMBWRkxAAACgPrYSqMBWRkxAAACgPrYS"
        + "qMBWRiRAAACgPrYSlMBWRkxAAACgPrYSlMBWRiRAAACgvrYSlMBWRkxAAACgvrYSlMBWRiRAAACg"
        + "vrYSqMBWRkxAAACgvrYSqMBWRiRAAACAPbYSpMBWRlxAAACAPbYSpMBWRkxAAACAPbYSmMBWRlxA"
        + "AACAPbYSmMBWRkxAAACAPbYSmMBWRlxAAACAPbYSmMBWRkxAAACAPbYSpMBWRlxAAACAPbYSpMBW"
        + "RkxAAACgPrYSvMBWRkxAAACgPrYSvMBWRiRAAACgPrYSqMBWRkxAAACgPrYSqMBWRiRAAACgvrYS"
        + "qMBWRkxAAACgvrYSqMBWRiRAAACgvrYSvMBWRkxAAACgvrYSvMBWRiRAAACAPbYSuMBWRlxAAACA"
        + "PbYSuMBWRkxAAACAPbYSrMBWRlxAAACAPbYSrMBWRkxAAACAPbYSrMBWRlxAAACAPbYSrMBWRkxA"
        + "AACAPbYSuMBWRlxAAACAPbYSuMBWRkxAAACgPrgS0MBWRkxAAACgPrgS0MBWRiRAAACgPrYSvMBW"
        + "RkxAAACgPrYSvMBWRiRAAACgvrYSvMBWRkxAAACgvrYSvMBWRiRAAACgvrgS0MBWRkxAAACgvrgS"
        + "0MBWRiRAAACAPbgSzMBWRlxAAACAPbgSzMBWRkxAAACAPbYSwMBWRlxAAACAPbYSwMBWRkxAAACA"
        + "PbYSwMBWRlxAAACAPbYSwMBWRkxAAACAPbgSzMBWRlxAAACAPbgSzMBWRkxAAACgPrgS5MBWRkxA"
        + "AACgPrgS5MBWRiRAAACgPrgS0MBWRkxAAACgPrgS0MBWRiRAAACgvrgS0MBWRkxAAACgvrgS0MBW"
        + "RiRAAACgvrgS5MBWRkxAAACgvrgS5MBWRiRAAACAPbgS4MBWRlxAAACAPbgS4MBWRkxAAACAPbgS"
        + "1MBWRlxAAACAPbgS1MBWRkxAAACAPbgS1MBWRlxAAACAPbgS1MBWRkxAAACAPbgS4MBWRlxAAACA"
        + "PbgS4MBWRkxAAACgPrgS+MBWRkxAAACgPrgS+MBWRiRAAACgPrgS5MBWRkxAAACgPrgS5MBWRiRA"
        + "AACgvrgS5MBWRkxAAACgvrgS5MBWRiRAAACgvrgS+MBWRkxAAACgvrgS+MBWRiRAAACAPbgS9MBW"
        + "RlxAAACAPbgS9MBWRkxAAACAPbgS6MBWRlxAAACAPbgS6MBWRkxAAACAPbgS6MBWRlxAAACAPbgS"
        + "6MBWRkxAAACAPbgS9MBWRlxAAACAPbgS9MBWRkxAAACgPlwJBsFWRkxAAACgPlwJBsFWRiRAAACg"
        + "PrgS+MBWRkxAAACgPrgS+MBWRiRAAACgvrgS+MBWRkxAAACgvrgS+MBWRiRAAACgvlwJBsFWRkxA"
        + "AACgvlwJBsFWRiRAAACAPVwJBMFWRlxAAACAPVwJBMFWRkxAAACAPbgS/MBWRlxAAACAPbgS/MBW"
        + "RkxAAACAPbgS/MBWRlxAAACAPbgS/MBWRkxAAACAPVwJBMFWRlxAAACAPVwJBMFWRkxAAACgPlwJ"
        + "EMFWRkxAAACgPlwJEMFSRiRAAACgPlwJBsFWRkxAAACgPlwJBsFWRiRAAACgvlwJBsFWRkxAAACg"
        + "vlwJBsFWRiRAAACgvlwJEMFWRkxAAACgvlwJEMFSRiRAAACAPVwJDsFWRlxAAACAPVwJDsFWRkxA"
        + "AACAPVwJCMFWRlxAAACAPVwJCMFWRkxAAACAPVwJCMFWRlxAAACAPVwJCMFWRkxAAACAPVwJDsFW"
        + "RlxAAACAPVwJDsFWRkxAAACIQCC1zz9WRlxAAACIQCC1zz9WRjxAAACIQJDaB0BWRlxAAACIQJDa"
        + "B0BWRjxAAABAP5DaB0BWRlxAAABAP5DaB0BWRjxAAABAPyC1zz9WRlxAAABAPyC1zz9WRjxAHwWI"
        + "QFtf4L+UUExAHwWIQFtf4L8ZPExAHwWIQJvJ3z+YUExAHwWIQJvJ3z8ZPExACtc/P5vJ3z+YUExA"
        + "Ctc/P5vJ3z8ZPExACtc/P1tf4L+UUExACtc/P1tf4L8ZPExAAACIwCC13z9WRlRAAACIwCC13z9W"
        + "RkRAAACIwCC1/z9WRlRAAACIwCC1/z9WRkRAAAD4wCC1/z9WRlRAAAD4wCC1/z9WRkRAAAD4wCC1"
        + "3z9WRlRAAAD4wCC13z9WRkRA3/qHwFtf4L+UUExA3/qHwFtf4L8ZPExA3/qHwJvJ3z+YUExA3/qH"
        + "wJvJ3z8ZPExAHwX4wJvJ3z+YUExAHwX4wJvJ3z8ZPExAHwX4wFtf4L+UUExAHwX4wFtf4L8ZPExA"
        + "AABAvyC1zz9WRlxAAABAvyC1zz9WRjxAAABAv5DaB0BWRlxAAABAv5DaB0BWRjxAAACIwJDaB0BW"
        + "RlxAAACIwJDaB0BWRjxAAACIwCC1zz9WRlxAAACIwCC1zz9WRjxACtc/v1tf4L+UUExACtc/v1tf"
        + "4L8ZPExACtc/v5vJ3z+YUExACtc/v5vJ3z8ZPExAHwWIwJvJ3z+YUExAHwWIwJvJ3z8ZPExAHwWI"
        + "wFtf4L+UUExAHwWIwFtf4L8ZPExAAAAAv78oKb/S/ENAAAAAvxwkGcDS/ANAAAAAv/2iJL7ajwxA"
        + "AAAAvzhI8r+0H5k/AADAv/2iJL7ajwxAAADAvzhI8r+0H5k/AADAv78oKb/S/ENAAADAvxwkGcDS"
        + "/ANAAADAPkrtz0BWRgxAAADAPkrtz0CsjPg/AADAPkrt70BWRgxAAADAPkrt70CsjPg/AADAvkrt"
        + "70BWRgxAAADAvkrt70CsjPg/AADAvkrtz0BWRgxAAADAvkrtz0CsjPg/AAAAv4gv/z+giSVAAAAA"
        + "v1xZIj+z7vk/AAAAv9odDUAniQhAAAAAv8VxWD/A7b8/AACAv9odDUAniQhAAACAv8VxWD/A7b8/"
        + "AACAv4gv/z+giSVAAACAv1xZIj+z7vk/AADIPwysf8B7vck/AADIP1EHicALmOg/AADIP5qwnsBq"
        + "o9o+AADIP+Xhp8DVBis/AADgPpqwnsBqo9o+AADgPuXhp8DVBis/AADgPgysf8B7vck/AADgPlEH"
        + "icALmOg/AADgvgysf8B7vck/AADgvlEHicALmOg/AADgvpqwnsBqo9o+AADgvuXhp8DVBis/AADI"
        + "v5qwnsBqo9o+AADIv+Xhp8DVBis/AADIvwysf8B7vck/AADIv1EHicALmOg/AABAP+BKwL9WRlBA"
        + "AABAP+BKwL+sjOA/AABAP5DaH0BWRlBAAABAP5DaH0CsjOA/AABAv5DaH0BWRlBAAABAv5DaH0Cs"
        + "jOA/AABAv+BKwL9WRlBAAABAv+BKwL+sjOA/AACAPSC1rz9WRmhAAACAPSC1rz9WRlBAAACAPZDa"
        + "B0BWRmhAAACAPZDaB0BWRlBAAACAPZDaB0BWRmhAAACAPZDaB0BWRlBAAACAPSC1rz9WRmhAAACA"
        + "PSC1rz9WRlBAAACAPQBS+z1WRmhAAACAPQBS+z1WRlBAAACAPUBqXz9WRmhAAACAPUBqXz9WRlBA"
        + "AACAPUBqXz9WRmhAAACAPUBqXz9WRlBAAACAPQBS+z1WRmhAAACAPQBS+z1WRlBAAACAPeBKkL9W"
        + "RmhAAACAPeBKkL9WRlBAAACAPYArwb5WRmhAAACAPYArwb5WRlBAAACAPYArwb5WRmhAAACAPYAr"
        + "wb5WRlBAAACAPeBKkL9WRmhAAACAPeBKkL9WRlBAAABwP+fEJj/ajvM/AABwPwaF0b5Kllc/AABw"
        + "P8Kmaj/tndE/AABwP6GCE75wtBM/AAAQP8Kmaj/tndE/AAAQP6GCE75wtBM/AAAQP+fEJj/ajvM/"
        + "AAAQPwaF0b5Kllc/AAAQv+fEJj/ajvM/AAAQvwaF0b5Kllc/AAAQv8Kmaj/tndE/AAAQv6GCE75w"
        + "tBM/AABwv8Kmaj/tndE/AABwv6GCE75wtBM/AABwv+fEJj/ajvM/AABwvwaF0b5Kllc/AAD4QCC1"
        + "3z9WRlRAAAD4QCC13z9WRkRAAAD4QCC1/z9WRlRAAAD4QCC1/z9WRkRAAACIQCC1/z9WRlRAAACI"
        + "QCC1/z9WRkRAAACIQCC13z9WRlRAAACIQCC13z9WRkRAHwX4QFtf4L+UUExAHwX4QFtf4L8ZPExA"
        + "HwX4QJvJ3z+YUExAHwX4QJvJ3z8ZPExA3/qHQJvJ3z+YUExA3/qHQJvJ3z8ZPExA3/qHQFtf4L+U"
        + "UExA3/qHQFtf4L8ZPExAAADAP78oKb/S/ENAAADAPxwkGcDS/ANAAADAP/2iJL7ajwxAAADAPzhI"
        + "8r+0H5k/AAAAP/2iJL7ajwxAAAAAPzhI8r+0H5k/AAAAP78oKb/S/ENAAAAAPxwkGcDS/ANAAACg"
        + "PpDaH0BWRjBAAACgPpDaH0BWRghAAACgPpTaR0BWRjBAAACgPpTaR0BWRghAAACgvpTaR0BWRjBA"
        + "AACgvpTaR0BWRghAAACgvpDaH0BWRjBAAACgvpDaH0BWRghAAACAPZDaJ0BWRkBAAACAPZDaJ0BW"
        + "RjBAAACAPZTaP0BWRkBAAACAPZTaP0BWRjBAAACAPZTaP0BWRkBAAACAPZTaP0BWRjBAAACAPZDa"
        + "J0BWRkBAAACAPZDaJ0BWRjBAAACgPpTaR0BWRjBAAACgPpTaR0BWRghAAACgPpTab0BWRjBAAACg"
        + "PpTab0BWRghAAACgvpTab0BWRjBAAACgvpTab0BWRghAAACgvpTaR0BWRjBAAACgvpTaR0BWRghA"
        + "AACAPZTaT0BWRkBAAACAPZTaT0BWRjBAAACAPZTaZ0BWRkBAAACAPZTaZ0BWRjBAAACAPZTaZ0BW"
        + "RkBAAACAPZTaZ0BWRjBAAACAPZTaT0BWRkBAAACAPZTaT0BWRjBAAACgPpTab0BWRjBAAACgPpTa"
        + "b0BWRghAAACgPkrti0BWRjBAAACgPkrti0BWRghAAACgvkrti0BWRjBAAACgvkrti0BWRghAAACg"
        + "vpTab0BWRjBAAACgvpTab0BWRghAAACAPZTad0BWRkBAAACAPZTad0BWRjBAAACAPUrth0BWRkBA"
        + "AACAPUrth0BWRjBAAACAPUrth0BWRkBAAACAPUrth0BWRjBAAACAPZTad0BWRkBAAACAPZTad0BW"
        + "RjBAAACgPkrti0BWRjBAAACgPkrti0BWRghAAACgPkrtn0BWRjBAAACgPkrtn0BWRghAAACgvkrt"
        + "n0BWRjBAAACgvkrtn0BWRghAAACgvkrti0BWRjBAAACgvkrti0BWRghAAACAPUrtj0BWRkBAAACA"
        + "PUrtj0BWRjBAAACAPUrtm0BWRkBAAACAPUrtm0BWRjBAAACAPUrtm0BWRkBAAACAPUrtm0BWRjBA"
        + "AACAPUrtj0BWRkBAAACAPUrtj0BWRjBAAACgPkrtn0BWRjBAAACgPkrtn0BWRghAAACgPkrts0BW"
        + "RjBAAACgPkrts0BWRghAAACgvkrts0BWRjBAAACgvkrts0BWRghAAACgvkrtn0BWRjBAAACgvkrt"
        + "n0BWRghAAACAPUrto0BWRkBAAACAPUrto0BWRjBAAACAPUrtr0BWRkBAAACAPUrtr0BWRjBAAACA"
        + "PUrtr0BWRkBAAACAPUrtr0BWRjBAAACAPUrto0BWRkBAAACAPUrto0BWRjBAAACAP4gv/z+giSVA"
        + "AACAP1xZIj+z7vk/AACAP9odDUAniQhAAACAP8VxWD/A7b8/AAAAP9odDUAniQhAAAAAP8VxWD/A"
        + "7b8/AAAAP4gv/z+giSVAAAAAP1xZIj+z7vk/";

    private static final String NORMALS_B64 =
        "fwAAgQAAAAB/AACBAIEAAH8AAH8LAIELAAt/AAuBAG5AAJLAAMBuAECSAHM2AI3KAMpzADaNAGGu"
        + "AJ9SAFJhAK6fAFpaAKamAKZaAFqm";

    private static final String UVS_B64 =
        "/wMwP/4PcD7/AzA/+feBPgH8Pz/+D3A+Afw/P/n3gT7/A0w//g9wPv8DTD/594E+AfxbP/4PcD4B"
        + "/Fs/+feBPgH8Sz8C8G8+AfxLP/4PMD7/A0A/AvBvPv8DQD/+DzA+AfxXP/4PMD4B/Fc/AvBvPv8D"
        + "TD/+DzA+/wNMPwLwbz7/A1w//g9wPv8DXD/594E+AfxnP/4PcD4B/Gc/+feBPv8DQD/+D3A+/wNA"
        + "P/n3gT4B/Es//g9wPgH8Sz/594E+/wfgPh8QOD7/B+A+4e93PgH4/z4fEDg+Afj/PuHvdz7/AxA/"
        + "HxA4Pv8DED/h73c+AfwfPx8QOD4B/B8/4e93PgH8Dz/h7zc+AfwPPz4g8D3/AwA/4e83Pv8DAD8+"
        + "IPA9AfwfPz4g8D0B/B8/4e83Pv8DED8+IPA9/wMQP+HvNz7/AyA/HxA4Pv8DID/h73c+AfwvPx8Q"
        + "OD4B/C8/4e93Pv8DAD8fEDg+/wMAP+Hvdz4B/A8/HxA4PgH8Dz/h73c+g79fPfqAwDyDv189g78f"
        + "Pfc/AD36gMA89z8APYO/Hz0Gf788+oDAPAZ/vzyDvx89AAAAAPqAwDwAAAAAg78fPfqAwDwGf788"
        + "+oDAPAAAAAATgP88Bn+/PBOA/zwAAAAA9z8APQAAAAD3PwA9Bn+/PIO/Hz0AAAAAg78fPQZ/vzwJ"
        + "wH89+oDAPAnAfz2Dvx89fUBgPfqAwDx9QGA9g78fPROA/zz6gMA8E4D/PIO/Hz36gMA8+oDAPPqA"
        + "wDyDvx898PfzPu1/gDzw9/M+Bn+/PBAI7D7tf4A8EAjsPgZ/vzwB+Oc+7X+APAH45z4Gf788/wfg"
        + "Pu1/gDz/B+A+Bn+/PP8H6D4mAH88/wfoPgAAAADw9+s+JgB/PPD36z4AAAAAEAjsPgAAAAAQCOw+"
        + "JgB/PAH47z4AAAAAAfjvPiYAfzwB+Pc+7X+APAH49z4Gf788EAj0Pu1/gDwQCPQ+Bn+/PPD36z7t"
        + "f4A88PfrPgZ/vzz/B+g+7X+APP8H6D4Gf788/wNEP/c/QD3/A0Q/AvAvPgH8Tz/3P0A9AfxPPwLw"
        + "Lz7/A1w/9z9APf8DXD8C8C8+AfxnP/c/QD0B/Gc/AvAvPgH8Wz8JwD89AfxbPwAAAAD/A1A/CcA/"
        + "Pf8DUD8AAAAAAfxnPwAAAAAB/Gc/CcA/Pf8DXD8AAAAA/wNcPwnAPz3/A2g/9z9APf8DaD8C8C8+"
        + "AfxzP/c/QD0B/HM/AvAvPv8DUD/3P0A9/wNQPwLwLz4B/Fs/9z9APQH8Wz8C8C8+/wMQP/8H8D7/"
        + "AxA/Afj3PgH8Hz//B/A+AfwfPwH49z7/Ayg//wfwPv8DKD8B+Pc+Afw3P/8H8D4B/Dc/Afj3PgH8"
        + "Jz8B+O8+AfwnP/8H0D7/AyA/AfjvPv8DID//B9A+AfwvP/8H0D4B/C8/AfjvPv8DKD//B9A+/wMo"
        + "PwH47z7/Azg//wfwPv8DOD8B+Pc+Afw/P/8H8D4B/D8/Afj3Pv8DID//B/A+/wMgPwH49z4B/Cc/"
        + "/wfwPgH8Jz8B+Pc+/wNAPxAI5D7/A0A/Afj3Pvj7ST8QCOQ++PtJPwH49z7/A1Q/EAjkPv8DVD8B"
        + "+Pc++PtdPxAI5D74+10/Afj3PgH8Uz/w9+M+AfxTP/8H0D4IBEo/8PfjPggESj//B9A++PtdP/8H"
        + "0D74+10/8PfjPv8DVD//B9A+/wNUP/D34z4IBF4/EAjkPggEXj8B+Pc+AfxnPxAI5D4B/Gc/Afj3"
        + "PggESj8QCOQ+CARKPwH49z4B/FM/EAjkPgH8Uz8B+Pc+/g9APvqAwDz+D0A+g78fPeHvVz76gMA8"
        + "4e9XPoO/Hz3+D2A++oDAPP4PYD6Dvx894e93PvqAwDzh73c+g78fPQLwXz4Gf788AvBfPgAAAAAf"
        + "EFg+Bn+/PB8QWD4AAAAA4e9nPgAAAADh72c+Bn+/PP4PYD4AAAAA/g9gPgZ/vzwfEHg++oDAPB8Q"
        + "eD6Dvx89AvB/PvqAwDwC8H8+g78fPR8QWD76gMA8HxBYPoO/Hz0C8F8++oDAPALwXz6Dvx89/wfg"
        + "Pv8HwD7/B+A+AfjPPgH47z7/B8A+AfjvPgH4zz7/AzA//wfAPv8DMD8B+M8+Afw3P/8HwD4B/Dc/"
        + "AfjPPgH8Lz8B+L8+AfwvP/8HsD7/B/A+Afi/Pv8H8D7/B7A+AfxnP/8HsD4B/Gc/Afi/Pv8DMD//"
        + "B7A+/wMwPwH4vz7/Azg//wfAPv8DOD8B+M8+AfxvP/8HwD4B/G8/AfjPPv8H8D7/B8A+/wfwPgH4"
        + "zz4B/C8//wfAPgH8Lz8B+M8+AvBfvv8DED8C8F++AfwPPwAAAAD/AxA/AAAAAAH8Dz/+D2A+/wMQ"
        + "P/4PYD4B/A8/AfjfPv8DED8B+N8+AfwPPwLwXz4B/A8/AvBfPv8HsD4AAAAAAfwPPwAAAAD/B7A+"
        + "AfjfPv8HsD7+D2A+/wewPv8H4D7/AxA//wfgPgH8Dz8B/Cc//wMQPwH8Jz8B/A8/AAAAAP8DED8C"
        + "8F8+/wMQPwH8Lz//Aww/AfwvPwH8Dz//Ayw//wMMP/8DLD8B/A8/AfjnPv8DDD8B+Oc+AfwPP/8H"
        + "4D7/Aww//wfoPgH8Cz//B+g+/wMIPwH8Kz8B/As/AfwrP/8DCD//Ayw//wMIP/8DLD8B/As/Afxj"
        + "P/8DCD8B/GM/AfwLPwH8Zz//Aww/AfxnPwH8Dz//AzA//wMMP/8DMD8B/A8/AfwrP/8DDD8B/Cs/"
        + "AfwPP/8H6D7/Aww//wfoPgH8Dz8B+N8+/wNIPwH43z4B/Ec//g9gPv8DSD/+D2A+AfxHPwAAAAD/"
        + "A0g/AAAAAAH8Rz8C8F++/wNIPwLwX74B/Ec/AAAAAAH8Rz8C8F8+AfxHPwH8Jz//A0g/AfwnPwH8"
        + "Rz//B+A+/wNIP/8H4D4B/Ec/AvBfPv8DSD8AAAAA/wNIPwLwPz77H4A9AvA/PgLwPz7+DwA++x+A"
        + "Pf4PAD4C8D8+CcB/PfsfgD0JwH89AvA/PgAAAAD7H4A9AAAAAALwPz77H4A9CcB/PfsfgD0AAAAA"
        + "BeD/PQnAfz0F4P89AAAAAP4PAD4AAAAA/g8APgnAfz0C8D8+AAAAAALwPz4JwH89AvB/PvsfgD0C"
        + "8H8+AvA/Pv4PQD77H4A9/g9APgLwPz4F4P89+x+APQXg/z0C8D8++x+APfsfgD37H4A9AvA/Pv8D"
        + "MD/2B6I+/wMwP/n3qT4B/D8/9geiPgH8Pz/596k+/wNMP/YHoj7/A0w/+fepPgH8Wz/2B6I+Afxb"
        + "P/n3qT4B/Es/+fehPgH8Sz/2B4I+/wNAP/n3oT7/A0A/9geCPgH8Vz/2B4I+AfxXP/n3oT7/A0w/"
        + "9geCPv8DTD/596E+/wNcP/YHoj7/A1w/+fepPgH8Zz/2B6I+AfxnP/n3qT7/A0A/9geiPv8DQD/5"
        + "96k+AfxLP/YHoj4B/Es/+fepPgH8Bz//B+A+AfwHPwH8Bz//AwA//wfgPv8DAD8B/Ac/AfjvPv8H"
        + "4D4B+O8+AfwHP/8H4D7/B+A+/wfgPgH8Bz//B/A+AfjfPv8H8D7/B9A+Afj/PgH43z4B+P8+/wfQ"
        + "Pv8DAD//B9A+/wMAPwH43z4B/Ac//wfQPgH8Bz8B+N8+AfwPP/8H4D4B/A8/AfwHP/8DCD//B+A+"
        + "/wMIPwH8Bz8B+P8+/wfgPgH4/z4B/Ac//wfwPv8H4D7/B/A+AfwHP/8H4D77H8A9/wfgPsLf7z0B"
        + "/Ac/+x/APQH8Bz/C3+89CAQaP/sfwD0IBBo/wt/vPfj7MT/7H8A9+PsxP8Lf7z34+xk/BeC/Pfj7"
        + "GT8AAAAA/wMIPwXgvz3/Awg/AAAAAAH8Kz8AAAAAAfwrPwXgvz0IBBo/AAAAAAgEGj8F4L89CAQy"
        + "P/sfwD0IBDI/wt/vPQH8Qz/7H8A9AfxDP8Lf7z3/Awg/+x/APf8DCD/C3+89+PsZP/sfwD34+xk/"
        + "wt/vPQAAAAD/B4A+AAAAAAH4rz4C8H8+/weAPgLwfz4B+K8+/wewPv8HgD7/B7A+AfivPgH8Fz//"
        + "B4A+AfwXPwH4rz4B+K8+AvB/PgH4rz4AAAAA/weAPgLwfz7/B4A+AAAAAAH43z4AAAAAAfjfPgLw"
        + "fz7/B7A+AAAAAP8HsD4C8H8+/wMYP/8HgD7/Axg/AfivPgH8Lz//B4A+AfwvPwH4rz7/B4A+/weA"
        + "Pv8HgD4B+K8+AfivPv8HgD4B+K8+AfivPv8DXD/2B4I+/wNcPwr4jT4B/Gc/9geCPgH8Zz8K+I0+"
        + "CARqP/YHgj4IBGo/CviNPvj7dT/2B4I++Pt1Pwr4jT74+2k/+feBPvj7aT/tD1Q+/wNoP/n3gT7/"
        + "A2g/7Q9UPgH8az/tD1Q+AfxrP/n3gT4IBGo/7Q9UPggEaj/594E+CAR2P/YHgj4IBHY/CviNPgH8"
        + "dz/2B4I+Afx3Pwr4jT7/A2g/9geCPv8DaD8K+I0++PtpP/YHgj74+2k/CviNPggEYj//AxA/CARi"
        + "PwH8Jz8B/Gc//wMQPwH8Zz8B/Cc/CARuP/8DED8IBG4/AfwnPwH8cz//AxA/AfxzPwH8Jz/4+20/"
        + "AfwPP/j7bT8IBAo//wNoPwH8Dz//A2g/CAQKPwH8cz8IBAo/AfxzPwH8Dz8IBG4/CAQKPwgEbj8B"
        + "/A8//wN0P/8DED//A3Q/AfwnP/j7eT//AxA/+Pt5PwH8Jz//A2g//wMQP/8DaD8B/Cc/+PttP/8D"
        + "ED/4+20/AfwnPw==";

    private static final String INDICES_B64 =
        "AAAAAAAAAQABAAAAAwADAAAAAgACAAAABAAEAAEABQAFAAEABwAHAAEABgAGAAEABAAIAAIABgAJ"
        + "AAIAAAALAAIAAgAKAAIABwAMAAMABQANAAMAAwAPAAMAAQAOAAMABgAQAAQABwARAAQAAQATAAQA"
        + "AAASAAQAAgAUAAUAAwAVAAUABQAXAAUABAAWAAUACAAYAAAACQAZAAAACwAbAAAACgAaAAAADAAc"
        + "AAEADQAdAAEADwAfAAEADgAeAAEADAAgAAIADgAhAAIACAAjAAIACgAiAAIADwAkAAMADQAlAAMA"
        + "CwAnAAMACQAmAAMADgAoAAQADwApAAQACQArAAQACAAqAAQACgAsAAUACwAtAAUADQAvAAUADAAu"
        + "AAUAEAAwAAAAEQAxAAAAEwAzAAAAEgAyAAAAFAA0AAEAFQA1AAEAFwA3AAEAFgA2AAEAFAA4AAIA"
        + "FgA5AAIAEAA7AAIAEgA6AAIAFwA8AAMAFQA9AAMAEwA/AAMAEQA+AAMAFgBAAAQAFwBBAAQAEQBD"
        + "AAQAEABCAAQAEgBEAAUAEwBFAAUAFQBHAAUAFABGAAUAGABIAAAAGQBJAAAAGwBLAAAAGgBKAAAA"
        + "HABMAAEAHQBNAAEAHwBPAAEAHgBOAAEAHABQAAIAHgBRAAIAGABTAAIAGgBSAAIAHwBUAAMAHQBV"
        + "AAMAGwBXAAMAGQBWAAMAHgBYAAQAHwBZAAQAGQBbAAQAGABaAAQAGgBcAAUAGwBdAAUAHQBfAAUA"
        + "HABeAAUAIAA2AAAAIQA3AAAAIwA1AAAAIgA0AAAAJAAyAAEAJQAzAAEAJwAxAAEAJgAwAAEAJAA6"
        + "AAIAJgA7AAIAIAA5AAIAIgA4AAIAJwA+AAMAJQA/AAMAIwA9AAMAIQA8AAMAJgBCAAQAJwBDAAQA"
        + "IQBBAAQAIABAAAQAIgBGAAUAIwBHAAUAJQBFAAUAJABEAAUAKABOAAAAKQBPAAAAKwBNAAAAKgBM"
        + "AAAALABKAAEALQBLAAEALwBJAAEALgBIAAEALABSAAIALgBTAAIAKABRAAIAKgBQAAIALwBWAAMA"
        + "LQBXAAMAKwBVAAMAKQBUAAMALgBaAAQALwBbAAQAKQBZAAQAKABYAAQAKgBeAAUAKwBfAAUALQBd"
        + "AAUALABcAAUAMABgAAAAMQBhAAAAMwBjAAAAMgBiAAAANABkAAEANQBlAAEANwBnAAEANgBmAAEA"
        + "NABoAAYANgBpAAYAMABrAAYAMgBqAAYANwBsAAcANQBtAAcAMwBvAAcAMQBuAAcANgBwAAgANwBx"
        + "AAgAMQBzAAgAMAByAAgAMgB0AAkAMwB1AAkANQB3AAkANAB2AAkAOABmAAAAOQBnAAAAOwBlAAAA"
        + "OgBkAAAAPABiAAEAPQBjAAEAPwBhAAEAPgBgAAEAPABqAAYAPgBrAAYAOABpAAYAOgBoAAYAPwBu"
        + "AAcAPQBvAAcAOwBtAAcAOQBsAAcAPgByAAgAPwBzAAgAOQBxAAgAOABwAAgAOgB2AAkAOwB3AAkA"
        + "PQB1AAkAPAB0AAkAQAB4AAAAQQB5AAAAQwB7AAAAQgB6AAAARAB8AAEARQB9AAEARwB/AAEARgB+"
        + "AAEARACAAAUARgCBAAUAQACDAAUAQgCCAAUARwCEAAQARQCFAAQAQwCHAAQAQQCGAAQARgCIAAIA"
        + "RwCJAAIAQQCLAAIAQACKAAIAQgCMAAMAQwCNAAMARQCPAAMARACOAAMASAB+AAAASQB/AAAASwB9"
        + "AAAASgB8AAAATAB6AAEATQB7AAEATwB5AAEATgB4AAEATACCAAUATgCDAAUASACBAAUASgCAAAUA"
        + "TwCGAAQATQCHAAQASwCFAAQASQCEAAQATgCKAAIATwCLAAIASQCJAAIASACIAAIASgCOAAMASwCP"
        + "AAMATQCNAAMATACMAAMAUACQAAAAUQCRAAAAUwCTAAAAUgCSAAAAVACUAAEAVQCVAAEAVwCXAAEA"
        + "VgCWAAEAVACYAAIAVgCZAAIAUACbAAIAUgCaAAIAVwCcAAMAVQCdAAMAUwCfAAMAUQCeAAMAVgCg"
        + "AAQAVwChAAQAUQCjAAQAUACiAAQAUgCkAAUAUwClAAUAVQCnAAUAVACmAAUAWACoAAAAWQCpAAAA"
        + "WwCrAAAAWgCqAAAAXACsAAEAXQCtAAEAXwCvAAEAXgCuAAEAXACwAAIAXgCxAAIAWACzAAIAWgCy"
        + "AAIAXwC0AAMAXQC1AAMAWwC3AAMAWQC2AAMAXgC4AAQAXwC5AAQAWQC7AAQAWAC6AAQAWgC8AAUA"
        + "WwC9AAUAXQC/AAUAXAC+AAUAYACQAAAAYQCRAAAAYwCTAAAAYgCSAAAAZACUAAEAZQCVAAEAZwCX"
        + "AAEAZgCWAAEAZACYAAIAZgCZAAIAYACbAAIAYgCaAAIAZwCcAAMAZQCdAAMAYwCfAAMAYQCeAAMA"
        + "ZgCgAAQAZwChAAQAYQCjAAQAYACiAAQAYgCkAAUAYwClAAUAZQCnAAUAZACmAAUAaACoAAAAaQCp"
        + "AAAAawCrAAAAagCqAAAAbACsAAEAbQCtAAEAbwCvAAEAbgCuAAEAbACwAAIAbgCxAAIAaACzAAIA"
        + "agCyAAIAbwC0AAMAbQC1AAMAawC3AAMAaQC2AAMAbgC4AAQAbwC5AAQAaQC7AAQAaAC6AAQAagC8"
        + "AAUAawC9AAUAbQC/AAUAbAC+AAUAcACQAAAAcQCRAAAAcwCTAAAAcgCSAAAAdACUAAEAdQCVAAEA"
        + "dwCXAAEAdgCWAAEAdACYAAIAdgCZAAIAcACbAAIAcgCaAAIAdwCcAAMAdQCdAAMAcwCfAAMAcQCe"
        + "AAMAdgCgAAQAdwChAAQAcQCjAAQAcACiAAQAcgCkAAUAcwClAAUAdQCnAAUAdACmAAUAeACoAAAA"
        + "eQCpAAAAewCrAAAAegCqAAAAfACsAAEAfQCtAAEAfwCvAAEAfgCuAAEAfACwAAIAfgCxAAIAeACz"
        + "AAIAegCyAAIAfwC0AAMAfQC1AAMAewC3AAMAeQC2AAMAfgC4AAQAfwC5AAQAeQC7AAQAeAC6AAQA"
        + "egC8AAUAewC9AAUAfQC/AAUAfAC+AAUAgACQAAAAgQCRAAAAgwCTAAAAggCSAAAAhACUAAEAhQCV"
        + "AAEAhwCXAAEAhgCWAAEAhACYAAIAhgCZAAIAgACbAAIAggCaAAIAhwCcAAMAhQCdAAMAgwCfAAMA"
        + "gQCeAAMAhgCgAAQAhwChAAQAgQCjAAQAgACiAAQAggCkAAUAgwClAAUAhQCnAAUAhACmAAUAiACo"
        + "AAAAiQCpAAAAiwCrAAAAigCqAAAAjACsAAEAjQCtAAEAjwCvAAEAjgCuAAEAjACwAAIAjgCxAAIA"
        + "iACzAAIAigCyAAIAjwC0AAMAjQC1AAMAiwC3AAMAiQC2AAMAjgC4AAQAjwC5AAQAiQC7AAQAiAC6"
        + "AAQAigC8AAUAiwC9AAUAjQC/AAUAjAC+AAUAkACQAAAAkQCRAAAAkwCTAAAAkgCSAAAAlACUAAEA"
        + "lQCVAAEAlwCXAAEAlgCWAAEAlACYAAIAlgCZAAIAkACbAAIAkgCaAAIAlwCcAAMAlQCdAAMAkwCf"
        + "AAMAkQCeAAMAlgCgAAQAlwChAAQAkQCjAAQAkACiAAQAkgCkAAUAkwClAAUAlQCnAAUAlACmAAUA"
        + "mACoAAAAmQCpAAAAmwCrAAAAmgCqAAAAnACsAAEAnQCtAAEAnwCvAAEAngCuAAEAnACwAAIAngCx"
        + "AAIAmACzAAIAmgCyAAIAnwC0AAMAnQC1AAMAmwC3AAMAmQC2AAMAngC4AAQAnwC5AAQAmQC7AAQA"
        + "mAC6AAQAmgC8AAUAmwC9AAUAnQC/AAUAnAC+AAUAoACQAAAAoQCRAAAAowCTAAAAogCSAAAApACU"
        + "AAEApQCVAAEApwCXAAEApgCWAAEApACYAAIApgCZAAIAoACbAAIAogCaAAIApwCcAAMApQCdAAMA"
        + "owCfAAMAoQCeAAMApgCgAAQApwChAAQAoQCjAAQAoACiAAQAogCkAAUAowClAAUApQCnAAUApACm"
        + "AAUAqACoAAAAqQCpAAAAqwCrAAAAqgCqAAAArACsAAEArQCtAAEArwCvAAEArgCuAAEArACwAAIA"
        + "rgCxAAIAqACzAAIAqgCyAAIArwC0AAMArQC1AAMAqwC3AAMAqQC2AAMArgC4AAQArwC5AAQAqQC7"
        + "AAQAqAC6AAQAqgC8AAUAqwC9AAUArQC/AAUArAC+AAUAsACQAAAAsQCRAAAAswCTAAAAsgCSAAAA"
        + "tACUAAEAtQCVAAEAtwCXAAEAtgCWAAEAtACYAAIAtgCZAAIAsACbAAIAsgCaAAIAtwCcAAMAtQCd"
        + "AAMAswCfAAMAsQCeAAMAtgCgAAQAtwChAAQAsQCjAAQAsACiAAQAsgCkAAUAswClAAUAtQCnAAUA"
        + "tACmAAUAuACoAAAAuQCpAAAAuwCrAAAAugCqAAAAvACsAAEAvQCtAAEAvwCvAAEAvgCuAAEAvACw"
        + "AAIAvgCxAAIAuACzAAIAugCyAAIAvwC0AAMAvQC1AAMAuwC3AAMAuQC2AAMAvgC4AAQAvwC5AAQA"
        + "uQC7AAQAuAC6AAQAugC8AAUAuwC9AAUAvQC/AAUAvAC+AAUAwACQAAAAwQCRAAAAwwCTAAAAwgCS"
        + "AAAAxACUAAEAxQCVAAEAxwCXAAEAxgCWAAEAxACYAAIAxgCZAAIAwACbAAIAwgCaAAIAxwCcAAMA"
        + "xQCdAAMAwwCfAAMAwQCeAAMAxgCgAAQAxwChAAQAwQCjAAQAwACiAAQAwgCkAAUAwwClAAUAxQCn"
        + "AAUAxACmAAUAyACoAAAAyQCpAAAAywCrAAAAygCqAAAAzACsAAEAzQCtAAEAzwCvAAEAzgCuAAEA"
        + "zACwAAIAzgCxAAIAyACzAAIAygCyAAIAzwC0AAMAzQC1AAMAywC3AAMAyQC2AAMAzgC4AAQAzwC5"
        + "AAQAyQC7AAQAyAC6AAQAygC8AAUAywC9AAUAzQC/AAUAzAC+AAUA0ACQAAAA0QCRAAAA0wCTAAAA"
        + "0gCSAAAA1ACUAAEA1QCVAAEA1wCXAAEA1gCWAAEA1ACYAAIA1gCZAAIA0ACbAAIA0gCaAAIA1wCc"
        + "AAMA1QCdAAMA0wCfAAMA0QCeAAMA1gCgAAQA1wChAAQA0QCjAAQA0ACiAAQA0gCkAAUA0wClAAUA"
        + "1QCnAAUA1ACmAAUA2ACoAAAA2QCpAAAA2wCrAAAA2gCqAAAA3ACsAAEA3QCtAAEA3wCvAAEA3gCu"
        + "AAEA3ACwAAIA3gCxAAIA2ACzAAIA2gCyAAIA3wC0AAMA3QC1AAMA2wC3AAMA2QC2AAMA3gC4AAQA"
        + "3wC5AAQA2QC7AAQA2AC6AAQA2gC8AAUA2wC9AAUA3QC/AAUA3AC+AAUA4ACQAAAA4QCRAAAA4wCT"
        + "AAAA4gCSAAAA5ACUAAEA5QCVAAEA5wCXAAEA5gCWAAEA5ACYAAIA5gCZAAIA4ACbAAIA4gCaAAIA"
        + "5wCcAAMA5QCdAAMA4wCfAAMA4QCeAAMA5gCgAAQA5wChAAQA4QCjAAQA4ACiAAQA4gCkAAUA4wCl"
        + "AAUA5QCnAAUA5ACmAAUA6ACoAAAA6QCpAAAA6wCrAAAA6gCqAAAA7ACsAAEA7QCtAAEA7wCvAAEA"
        + "7gCuAAEA7ACwAAIA7gCxAAIA6ACzAAIA6gCyAAIA7wC0AAMA7QC1AAMA6wC3AAMA6QC2AAMA7gC4"
        + "AAQA7wC5AAQA6QC7AAQA6AC6AAQA6gC8AAUA6wC9AAUA7QC/AAUA7AC+AAUA8ACQAAAA8QCRAAAA"
        + "8wCTAAAA8gCSAAAA9ACUAAEA9QCVAAEA9wCXAAEA9gCWAAEA9ACYAAIA9gCZAAIA8ACbAAIA8gCa"
        + "AAIA9wCcAAMA9QCdAAMA8wCfAAMA8QCeAAMA9gCgAAQA9wChAAQA8QCjAAQA8ACiAAQA8gCkAAUA"
        + "8wClAAUA9QCnAAUA9ACmAAUA+ACoAAAA+QCpAAAA+wCrAAAA+gCqAAAA/ACsAAEA/QCtAAEA/wCv"
        + "AAEA/gCuAAEA/ACwAAIA/gCxAAIA+ACzAAIA+gCyAAIA/wC0AAMA/QC1AAMA+wC3AAMA+QC2AAMA"
        + "/gC4AAQA/wC5AAQA+QC7AAQA+AC6AAQA+gC8AAUA+wC9AAUA/QC/AAUA/AC+AAUAAAGQAAAAAQGR"
        + "AAAAAwGTAAAAAgGSAAAABAGUAAEABQGVAAEABwGXAAEABgGWAAEABAGYAAIABgGZAAIAAAGbAAIA"
        + "AgGaAAIABwGcAAMABQGdAAMAAwGfAAMAAQGeAAMABgGgAAQABwGhAAQAAQGjAAQAAAGiAAQAAgGk"
        + "AAUAAwGlAAUABQGnAAUABAGmAAUACAGoAAAACQGpAAAACwGrAAAACgGqAAAADAGsAAEADQGtAAEA"
        + "DwGvAAEADgGuAAEADAGwAAIADgGxAAIACAGzAAIACgGyAAIADwG0AAMADQG1AAMACwG3AAMACQG2"
        + "AAMADgG4AAQADwG5AAQACQG7AAQACAG6AAQACgG8AAUACwG9AAUADQG/AAUADAG+AAUAEAHAAAAA"
        + "EQHBAAAAEwHDAAAAEgHCAAAAFAHEAAEAFQHFAAEAFwHHAAEAFgHGAAEAFAHIAAIAFgHJAAIAEAHL"
        + "AAIAEgHKAAIAFwHMAAMAFQHNAAMAEwHPAAMAEQHOAAMAFgHQAAQAFwHRAAQAEQHTAAQAEAHSAAQA"
        + "EgHUAAUAEwHVAAUAFQHXAAUAFAHWAAUAGAHYAAAAGQHZAAAAGwHbAAAAGgHaAAAAHAHcAAEAHQHd"
        + "AAEAHwHfAAEAHgHeAAEAHAHgAAIAHgHhAAIAGAHjAAIAGgHiAAIAHwHkAAMAHQHfAAMAGwHdAAMA"
        + "GQHlAAMAHgHmAAQAHwHnAAQAGQHpAAQAGAHoAAQAGgHqAAUAGwHiAAUAHQHgAAUAHAHrAAUAIAHs"
        + "AAAAIQHtAAAAIwHvAAAAIgHuAAAAJAHwAAEAJQHxAAEAJwHnAAEAJgHyAAEAJAHzAAIAJgH0AAIA"
        + "IAH2AAIAIgH1AAIAJwH3AAMAJQH4AAMAIwH6AAMAIQH5AAMAJgH7AAQAJwH8AAQAIQH+AAQAIAH9"
        + "AAQAIgH/AAUAIwEAAQUAJQECAQUAJAEBAQUAKAEDAQAAKQEEAQAAKwEGAQAAKgEFAQAALAEHAQEA"
        + "LQEIAQEALwEKAQEALgEJAQEALAELAQIALgHqAAIAKAHrAAIAKgEMAQIALwHcAAMALQEGAQMAKwEE"
        + "AQMAKQHeAAMALgENAQQALwEOAQQAKQEQAQQAKAEPAQQAKgERAQUAKwEMAQUALQELAQUALAESAQUA"
        + "MAHGAAAAMQHHAAAAMwHFAAAAMgHEAAAANAHCAAEANQHDAAEANwHBAAEANgHAAAEANAHKAAIANgHL"
        + "AAIAMAHJAAIAMgHIAAIANwHOAAMANQHPAAMAMwHNAAMAMQHMAAMANgHSAAQANwHTAAQAMQHRAAQA"
        + "MAHQAAQAMgHWAAUAMwHXAAUANQHVAAUANAHUAAUAOAHeAAAAOQHfAAAAOwHdAAAAOgHcAAAAPAHa"
        + "AAEAPQHbAAEAPwHZAAEAPgHYAAEAPAHiAAIAPgHjAAIAOAHhAAIAOgHgAAIAPwHlAAMAPQHdAAMA"
        + "OwHfAAMAOQHkAAMAPgHoAAQAPwHpAAQAOQHnAAQAOAHmAAQAOgHrAAUAOwHgAAUAPQHiAAUAPAHq"
        + "AAUAQAETAQAAQQEUAQAAQwEWAQAAQgEVAQAARAEXAQEARQEYAQEARwEaAQEARgEZAQEARAEbAQoA"
        + "RgEcAQoAQAEeAQoAQgEdAQoARwEfAQsARQEgAQsAQwEiAQsAQQEhAQsARgEjAQwARwEkAQwAQQEm"
        + "AQwAQAElAQwAQgEnAQ0AQwEoAQ0ARQEqAQ0ARAEpAQ0ASAErAQAASQEsAQAASwEuAQAASgEtAQAA"
        + "TAEvAQEATQEwAQEATwEyAQEATgExAQEATAEzAQIATgE0AQIASAE2AQIASgE1AQIATwE3AQMATQE4"
        + "AQMASwE6AQMASQE5AQMATgE7AQQATwE8AQQASQE+AQQASAE9AQQASgE/AQUASwFAAQUATQFCAQUA"
        + "TAFBAQUAUAFDAQAAUQFEAQAAUwFGAQAAUgFFAQAAVAFHAQEAVQFIAQEAVwFKAQEAVgFJAQEAVAFL"
        + "AQ4AVgFMAQ4AUAFOAQ4AUgFNAQ4AVwFPAQ8AVQFQAQ8AUwFSAQ8AUQFRAQ8AVgFTARAAVwFUARAA"
        + "UQFWARAAUAFVARAAUgFXAREAUwFYAREAVQFaAREAVAFZAREAWAFbAQAAWQFcAQAAWwFeAQAAWgFd"
        + "AQAAXAFfAQEAXQFgAQEAXwFiAQEAXgFhAQEAXAFjARIAXgFkARIAWAFmARIAWgFlARIAXwFnARMA"
        + "XQFoARMAWwFqARMAWQFpARMAXgFrARQAXwFsARQAWQFuARQAWAFtARQAWgFvARUAWwFwARUAXQFy"
        + "ARUAXAFxARUAYAFhAQAAYQFiAQAAYwFgAQAAYgFfAQAAZAFdAQEAZQFeAQEAZwFcAQEAZgFbAQEA"
        + "ZAFlARIAZgFmARIAYAFkARIAYgFjARIAZwFpARMAZQFqARMAYwFoARMAYQFnARMAZgFtARQAZwFu"
        + "ARQAYQFsARQAYAFrARQAYgFxARUAYwFyARUAZQFwARUAZAFvARUAaAFzAQAAaQF0AQAAawF2AQAA"
        + "agF1AQAAbAF3AQEAbQF4AQEAbwF6AQEAbgF5AQEAbAF7AQIAbgF8AQIAaAF+AQIAagF9AQIAbwF/"
        + "AQMAbQGAAQMAawGCAQMAaQGBAQMAbgGDAQQAbwGEAQQAaQGGAQQAaAGFAQQAagGHAQUAawGIAQUA"
        + "bQGKAQUAbAGJAQUAcAGLAQAAcQGMAQAAcwGOAQAAcgGNAQAAdAGPAQEAdQGQAQEAdwGSAQEAdgGR"
        + "AQEAdAGTAQIAdgGUAQIAcAGWAQIAcgGVAQIAdwGXAQMAdQGYAQMAcwGaAQMAcQGZAQMAdgGbAQQA"
        + "dwGcAQQAcQGeAQQAcAGdAQQAcgGfAQUAcwGgAQUAdQGiAQUAdAGhAQUAeAGLAQAAeQGMAQAAewGO"
        + "AQAAegGNAQAAfAGPAQEAfQGQAQEAfwGSAQEAfgGRAQEAfAGTAQIAfgGUAQIAeAGWAQIAegGVAQIA"
        + "fwGXAQMAfQGYAQMAewGaAQMAeQGZAQMAfgGbAQQAfwGcAQQAeQGeAQQAeAGdAQQAegGfAQUAewGg"
        + "AQUAfQGiAQUAfAGhAQUAgAGLAQAAgQGMAQAAgwGOAQAAggGNAQAAhAGPAQEAhQGQAQEAhwGSAQEA"
        + "hgGRAQEAhAGTAQIAhgGUAQIAgAGWAQIAggGVAQIAhwGXAQMAhQGYAQMAgwGaAQMAgQGZAQMAhgGb"
        + "AQQAhwGcAQQAgQGeAQQAgAGdAQQAggGfAQUAgwGgAQUAhQGiAQUAhAGhAQUAiAGjAQAAiQGkAQAA"
        + "iwGmAQAAigGlAQAAjAGnAQEAjQGoAQEAjwGqAQEAjgGpAQEAjAGrARYAjgGsARYAiAGuARYAigGt"
        + "ARYAjwGvARcAjQGwARcAiwGyARcAiQGxARcAjgGzARgAjwG0ARgAiQG2ARgAiAG1ARgAigG3ARkA"
        + "iwG4ARkAjQG6ARkAjAG5ARkAkAGpAQAAkQGqAQAAkwGoAQAAkgGnAQAAlAGlAQEAlQGmAQEAlwGk"
        + "AQEAlgGjAQEAlAGtARYAlgGuARYAkAGsARYAkgGrARYAlwGxARcAlQGyARcAkwGwARcAkQGvARcA"
        + "lgG1ARgAlwG2ARgAkQG0ARgAkAGzARgAkgG5ARkAkwG6ARkAlQG4ARkAlAG3ARkAmAHyAAAAmQHn"
        + "AAAAmwHxAAAAmgHwAAAAnAHuAAEAnQHvAAEAnwHtAAEAngHsAAEAnAH1AAIAngH2AAIAmAH0AAIA"
        + "mgHzAAIAnwH5AAMAnQH6AAMAmwH4AAMAmQH3AAMAngH9AAQAnwH+AAQAmQH8AAQAmAH7AAQAmgEB"
        + "AQUAmwECAQUAnQEAAQUAnAH/AAUAoAEJAQAAoQEKAQAAowEIAQAAogEHAQAApAEFAQEApQEGAQEA"
        + "pwEEAQEApgEDAQEApAEMAQIApgHrAAIAoAHqAAIAogELAQIApwHeAAMApQEEAQMAowEGAQMAoQHc"
        + "AAMApgEPAQQApwEQAQQAoQEOAQQAoAENAQQAogESAQUAowELAQUApQEMAQUApAERAQUAqAEZAQAA"
        + "qQEaAQAAqwEYAQAAqgEXAQAArAEVAQEArQEWAQEArwEUAQEArgETAQEArAEdAQoArgEeAQoAqAEc"
        + "AQoAqgEbAQoArwEhAQsArQEiAQsAqwEgAQsAqQEfAQsArgElAQwArwEmAQwAqQEkAQwAqAEjAQwA"
        + "qgEpAQ0AqwEqAQ0ArQEoAQ0ArAEnAQ0AsAGQAAAAsQGRAAAAswGTAAAAsgGSAAAAtAGUAAEAtQGV"
        + "AAEAtwGXAAEAtgGWAAEAtAGYAAIAtgGZAAIAsAGbAAIAsgGaAAIAtwGcAAMAtQGdAAMAswGfAAMA"
        + "sQGeAAMAtgGgAAQAtwGhAAQAsQGjAAQAsAGiAAQAsgGkAAUAswGlAAUAtQGnAAUAtAGmAAUAuAGo"
        + "AAAAuQGpAAAAuwGrAAAAugGqAAAAvAGsAAEAvQGtAAEAvwGvAAEAvgGuAAEAvAGwAAIAvgGxAAIA"
        + "uAGzAAIAugGyAAIAvwG0AAMAvQG1AAMAuwG3AAMAuQG2AAMAvgG4AAQAvwG5AAQAuQG7AAQAuAG6"
        + "AAQAugG8AAUAuwG9AAUAvQG/AAUAvAG+AAUAwAGQAAAAwQGRAAAAwwGTAAAAwgGSAAAAxAGUAAEA"
        + "xQGVAAEAxwGXAAEAxgGWAAEAxAGYAAIAxgGZAAIAwAGbAAIAwgGaAAIAxwGcAAMAxQGdAAMAwwGf"
        + "AAMAwQGeAAMAxgGgAAQAxwGhAAQAwQGjAAQAwAGiAAQAwgGkAAUAwwGlAAUAxQGnAAUAxAGmAAUA"
        + "yAGoAAAAyQGpAAAAywGrAAAAygGqAAAAzAGsAAEAzQGtAAEAzwGvAAEAzgGuAAEAzAGwAAIAzgGx"
        + "AAIAyAGzAAIAygGyAAIAzwG0AAMAzQG1AAMAywG3AAMAyQG2AAMAzgG4AAQAzwG5AAQAyQG7AAQA"
        + "yAG6AAQAygG8AAUAywG9AAUAzQG/AAUAzAG+AAUA0AGQAAAA0QGRAAAA0wGTAAAA0gGSAAAA1AGU"
        + "AAEA1QGVAAEA1wGXAAEA1gGWAAEA1AGYAAIA1gGZAAIA0AGbAAIA0gGaAAIA1wGcAAMA1QGdAAMA"
        + "0wGfAAMA0QGeAAMA1gGgAAQA1wGhAAQA0QGjAAQA0AGiAAQA0gGkAAUA0wGlAAUA1QGnAAUA1AGm"
        + "AAUA2AGoAAAA2QGpAAAA2wGrAAAA2gGqAAAA3AGsAAEA3QGtAAEA3wGvAAEA3gGuAAEA3AGwAAIA"
        + "3gGxAAIA2AGzAAIA2gGyAAIA3wG0AAMA3QG1AAMA2wG3AAMA2QG2AAMA3gG4AAQA3wG5AAQA2QG7"
        + "AAQA2AG6AAQA2gG8AAUA2wG9AAUA3QG/AAUA3AG+AAUA4AGQAAAA4QGRAAAA4wGTAAAA4gGSAAAA"
        + "5AGUAAEA5QGVAAEA5wGXAAEA5gGWAAEA5AGYAAIA5gGZAAIA4AGbAAIA4gGaAAIA5wGcAAMA5QGd"
        + "AAMA4wGfAAMA4QGeAAMA5gGgAAQA5wGhAAQA4QGjAAQA4AGiAAQA4gGkAAUA4wGlAAUA5QGnAAUA"
        + "5AGmAAUA6AGoAAAA6QGpAAAA6wGrAAAA6gGqAAAA7AGsAAEA7QGtAAEA7wGvAAEA7gGuAAEA7AGw"
        + "AAIA7gGxAAIA6AGzAAIA6gGyAAIA7wG0AAMA7QG1AAMA6wG3AAMA6QG2AAMA7gG4AAQA7wG5AAQA"
        + "6QG7AAQA6AG6AAQA6gG8AAUA6wG9AAUA7QG/AAUA7AG+AAUA8AGQAAAA8QGRAAAA8wGTAAAA8gGS"
        + "AAAA9AGUAAEA9QGVAAEA9wGXAAEA9gGWAAEA9AGYAAIA9gGZAAIA8AGbAAIA8gGaAAIA9wGcAAMA"
        + "9QGdAAMA8wGfAAMA8QGeAAMA9gGgAAQA9wGhAAQA8QGjAAQA8AGiAAQA8gGkAAUA8wGlAAUA9QGn"
        + "AAUA9AGmAAUA+AGoAAAA+QGpAAAA+wGrAAAA+gGqAAAA/AGsAAEA/QGtAAEA/wGvAAEA/gGuAAEA"
        + "/AGwAAIA/gGxAAIA+AGzAAIA+gGyAAIA/wG0AAMA/QG1AAMA+wG3AAMA+QG2AAMA/gG4AAQA/wG5"
        + "AAQA+QG7AAQA+AG6AAQA+gG8AAUA+wG9AAUA/QG/AAUA/AG+AAUAAAJJAQAAAQJKAQAAAwJIAQAA"
        + "AgJHAQAABAJFAQEABQJGAQEABwJEAQEABgJDAQEABAJNAQ4ABgJOAQ4AAAJMAQ4AAgJLAQ4ABwJR"
        + "AQ8ABQJSAQ8AAwJQAQ8AAQJPAQ8ABgJVARAABwJWARAAAQJUARAAAAJTARAAAgJZAREAAwJaAREA"
        + "BQJYAREABAJXAREA";

    private static final String JOINT_IDS_B64 =
        "JAAAACQAAAAkAAAAJAAAACQAAAAkAAAAJAAAACQAAAAjAAAAIwAAACMAAAAjAAAAIwAAACMAAAAj"
        + "AAAAIwAAACMAAAAjAAAAIwAAACMAAAAjAAAAIwAAACMAAAAjAAAAJAAAACQAAAAkAAAAJAAAACQA"
        + "AAAkAAAAJAAAACQAAAAjAAAAIwAAACMAAAAjAAAAIwAAACMAAAAjAAAAIwAAACQAAAAkAAAAJAAA"
        + "ACQAAAAkAAAAJAAAACQAAAAkAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAAFAAAA"
        + "BQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAABYAAAAWAAAAFgAAABYAAAAWAAAAFgAAABYAAAAW"
        + "AAAAGQAAABkAAAAZAAAAGQAAABkAAAAZAAAAGQAAABkAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgA"
        + "AAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACQAAAAkAAAAJAAAACQAA"
        + "AAkAAAAJAAAACQAAAAkAAAAJAAAACQAAAAkAAAAJAAAACQAAAAkAAAAJAAAACQAAAAoAAAAKAAAA"
        + "CgAAAAoAAAAKAAAACgAAAAoAAAAKAAAACgAAAAoAAAAKAAAACgAAAAoAAAAKAAAACgAAAAoAAAAL"
        + "AAAACwAAAAsAAAALAAAACwAAAAsAAAALAAAACwAAAAsAAAALAAAACwAAAAsAAAALAAAACwAAAAsA"
        + "AAALAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAA"
        + "AAwAAAAMAAAADAAAAA0AAAANAAAADQAAAA0AAAANAAAADQAAAA0AAAANAAAADQAAAA0AAAANAAAA"
        + "DQAAAA0AAAANAAAADQAAAA0AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADgAAAA4AAAAO"
        + "AAAADgAAAA4AAAAOAAAADgAAAA4AAAAOAAAADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAADwAAAA8A"
        + "AAAPAAAADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAADwAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAA"
        + "ABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAARAAAAEQAAABEAAAARAAAA"
        + "EQAAABEAAAARAAAAEQAAABEAAAARAAAAEQAAABEAAAARAAAAEQAAABEAAAARAAAAEgAAABIAAAAS"
        + "AAAAEgAAABIAAAASAAAAEgAAABIAAAASAAAAEgAAABIAAAASAAAAEgAAABIAAAASAAAAEgAAABMA"
        + "AAATAAAAEwAAABMAAAATAAAAEwAAABMAAAATAAAAEwAAABMAAAATAAAAEwAAABMAAAATAAAAEwAA"
        + "ABMAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAAGgAAABoAAAAaAAAA"
        + "GgAAABoAAAAaAAAAHQAAAB0AAAAdAAAAHQAAAB0AAAAdAAAAHQAAAB0AAAAdAAAAHQAAAB0AAAAd"
        + "AAAAHQAAAB0AAAAdAAAAHQAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwA"
        + "AAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAA"
        + "ACUAAAAlAAAAJQAAACUAAAAlAAAAJQAAACUAAAAlAAAAFwAAABcAAAAXAAAAFwAAABcAAAAXAAAA"
        + "FwAAABcAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAYAAAAGAAAABgAAAAYAAAAG"
        + "AAAABgAAAAYAAAAGAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcA"
        + "AAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAA"
        + "AAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAVAAAAFQAAABUAAAAVAAAAFQAAABUAAAAVAAAA"
        + "FQAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGwAAABsAAAAbAAAAGwAAABsAAAAb"
        + "AAAAGwAAABsAAAAbAAAAGwAAABsAAAAbAAAAGwAAABsAAAAbAAAAGwAAAAEAAAABAAAAAQAAAAEA"
        + "AAABAAAAAQAAAAEAAAABAAAAHgAAAB4AAAAeAAAAHgAAAB4AAAAeAAAAHgAAAB4AAAAeAAAAHgAA"
        + "AB4AAAAeAAAAHgAAAB4AAAAeAAAAHgAAAB8AAAAfAAAAHwAAAB8AAAAfAAAAHwAAAB8AAAAfAAAA"
        + "HwAAAB8AAAAfAAAAHwAAAB8AAAAfAAAAHwAAAB8AAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAg"
        + "AAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIQAAACEAAAAhAAAAIQAAACEA"
        + "AAAhAAAAIQAAACEAAAAhAAAAIQAAACEAAAAhAAAAIQAAACEAAAAhAAAAIQAAACIAAAAiAAAAIgAA"
        + "ACIAAAAiAAAAIgAAACIAAAAiAAAAIgAAACIAAAAiAAAAIgAAACIAAAAiAAAAIgAAACIAAAAUAAAA"
        + "FAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAAA==";

    private static float[] decodeFloats(String b64) {
        byte[] bytes = Base64.getDecoder().decode(b64.replace("\n", ""));
        float[] result = new float[bytes.length / 4];
        ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asFloatBuffer().get(result);
        return result;
    }

    private static int[] decodeInts() {
        byte[] bytes = Base64.getDecoder().decode(DragonMeshData.JOINT_IDS_B64.replace("\n", ""));
        int[] result = new int[bytes.length / 4];
        ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asIntBuffer().get(result);
        return result;
    }

    private static int[] decodeShortsToInts() {
        byte[] bytes = Base64.getDecoder().decode(DragonMeshData.INDICES_B64.replace("\n", ""));
        int count = bytes.length / 2;
        int[] result = new int[count];
        java.nio.ShortBuffer sb = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer();
        for (int i = 0; i < count; i++) {
            result[i] = sb.get(i) & 0xFFFF;
        }
        return result;
    }

    private static float[] decodeNormalBytes() {
        byte[] bytes = Base64.getDecoder().decode(DragonMeshData.NORMALS_B64.replace("\n", ""));
        float[] result = new float[bytes.length];
        for (int i = 0; i < bytes.length; i++) {
            result[i] = (float)(bytes[i] & 0xFF) / 127.0F;
            if (result[i] > 1.0F) result[i] -= 2.0F;
        }
        return result;
    }

    public static Mesh createMesh() {
        float[] positionArray = decodeFloats(POSITIONS_B64);
        for (int i = 0; i < positionArray.length / 3; i++) {
            int k = i * 3;
            Vector4f posVector = new Vector4f(positionArray[k], positionArray[k+1], positionArray[k+2], 1.0F);
            OpenMatrix4f.transform(CORRECTION, posVector, posVector);
            positionArray[k] = posVector.x;
            positionArray[k+1] = posVector.y;
            positionArray[k+2] = posVector.z;
        }

        float[] normalArray = decodeNormalBytes();
        for (int i = 0; i < normalArray.length / 3; i++) {
            int k = i * 3;
            Vector4f normVector = new Vector4f(normalArray[k], normalArray[k+1], normalArray[k+2], 1.0F);
            OpenMatrix4f.transform(CORRECTION, normVector, normVector);
            normalArray[k] = normVector.x;
            normalArray[k+1] = normVector.y;
            normalArray[k+2] = normVector.z;
        }

        int[] drawingIndices = decodeShortsToInts();
        int[] jointIds = decodeInts();
        int[] vcounts = new int[VERTEX_COUNT];
        java.util.Arrays.fill(vcounts, 1);

        return new Mesh(positionArray, normalArray, decodeFloats(UVS_B64), jointIds, drawingIndices, vcounts);
    }
}
